const Objects = [
    {
        id: 1,
        img: "../img/Perfil1.png",
        name: "Carlos Sanchez",
        email: "carlos@developer.com",
        genderIdentity: "He/Him",
        position: "Front Developer",
        stackDescription: "Junior Front Developer with experience in HTML5, CSS3, JavaScript and React.",
    },
    {
        id: 2,
        img: "../img/Perfil1.png",
        name: "Ana Delgado",
        email: "ana@developer.com",
        genderIdentity: "She/Her",
        position: "Full Stack Developer",
        stackDescription: "Junior Full Stack Developer with experience in HTML5, CSS3, JavaScript, React, PHP and symphony.",
    },
    {
        id: 3,
        img: "../img/Perfil1.png",
        name: "Alba Rus",
        email: "alba@developer.com",
        genderIdentity: "She/Her",
        position: "Back Developer",
        stackDescription: "Junior Back Developer with experience in HTML5, CSS3, JavaScript, PHP, Laravel and MySQL.",
    },
    {
        id: 4,
        img: "../img/Perfil1.png",
        name: "Ainhoa Cala",
        email: "ainhoa@developer.com",
        genderIdentity: "She/Her",
        position: "Front Developer",
        stackDescription: "Junior Front Developer with experience in HTML5, CSS3, JavaScript and React.",
    },
]